name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@uor-foundation'

      - run: npm ci
      - run: npm test
      - run: npm run build

      - name: Publish packages to NPM
        run: |
          # Test authentication
          npm whoami --registry https://registry.npmjs.org

          # Publish each package individually
          for package in packages/*/; do
            if [ -d "$package" ] && [ -f "$package/package.json" ]; then
              if ! grep -q '"private": true' "$package/package.json"; then
                echo "Publishing $package"
                cd "$package"
                npm publish --registry https://registry.npmjs.org
                cd ../..
              fi
            fi
          done

          # Publish MCP server
          if [ -d "apps/mcp-server" ] && [ -f "apps/mcp-server/package.json" ]; then
            if ! grep -q '"private": true' "apps/mcp-server/package.json"; then
              echo "Publishing apps/mcp-server"
              cd apps/mcp-server
              npm publish --registry https://registry.npmjs.org
              cd ../..
            fi
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY }}
