name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@uor-foundation'

      - run: npm ci

      - run: npm test

      - run: npm run build

      - name: Publish to NPM
        run: npx lerna publish from-package --registry https://registry.npmjs.org --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY }}